### ISSUE TITLE
gogoanime NoneType has no attrs

### ISSUE THREAD

**Issue by phanirithvij** [vn-ki/anime-downloader#499] opened 2020-08-30 12:25 UTC
**Describe the bug**

Gogoanime is broken

**To reproduce**

```
anime -ll DEBUG dl "https://gogoanime.app/anime/gintama-movie-2-kanketsu-hen-yorozuya-yo-eien-nare-jlk3"
```

<details>
<summary>LOG</summary>

```

2020-08-30 17:53:02 RithvijL anime_downloader.util[2236] INFO anime-downloader 4.6.3
2020-08-30 17:53:02 RithvijL anime_downloader.util[2236] DEBUG Platform: Windows-10-10.0.19041-SP0
2020-08-30 17:53:02 RithvijL anime_downloader.util[2236] DEBUG Python 3.8.0
2020-08-30 17:53:02 RithvijL anime_downloader.sites.anime[2236] INFO Extracting episode info from page
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG -----
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG GET https://gogoanime.app/anime/gintama-movie-2-kanketsu-hen-yorozuya-yo-eien-nare-jlk3
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG {}
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/4.0.213.1 Safari/532.1'}
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG -----
2020-08-30 17:53:02 RithvijL anime_downloader.session[2236] DEBUG cached request
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG https://gogoanime.app/anime/gintama-movie-2-kanketsu-hen-yorozuya-yo-eien-nare-jlk3
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG C:\Users\Rithvij\AppData\Local\Temp\animedlgrt1rqtr\tmph088v68q
2020-08-30 17:53:02 RithvijL anime_downloader.sites.anime[2236] DEBUG Metadata scraping error: 'NoneType' object has no attribute 'find'2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG -----
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG GET https://gogoanime.app/anime/gintama-movie-2-kanketsu-hen-yorozuya-yo-eien-nare-jlk3
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG {}
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/4.0.213.1 Safari/532.1'}
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG -----
2020-08-30 17:53:02 RithvijL anime_downloader.session[2236] DEBUG cached request
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG https://gogoanime.app/anime/gintama-movie-2-kanketsu-hen-yorozuya-yo-eien-nare-jlk3
2020-08-30 17:53:02 RithvijL anime_downloader.sites.helpers.request[2236] DEBUG C:\Users\Rithvij\AppData\Local\Temp\animedlgrt1rqtr\tmpeoi9nl1s
Traceback (most recent call last):
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Rithvij\AppData\Local\Programs\Python\Python38\Scripts\anime.exe\__main__.py", line 7, in <module>
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\anime_downloader\cli.py", line 53, in main
    cli()
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\anime_downloader\commands\dl.py", line 101, in command
    anime = cls(anime_url, quality=quality,
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\anime_downloader\sites\anime.py", line 84, in __init__
    self._episode_urls = self.get_data()
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\anime_downloader\sites\anime.py", line 165, in get_data
    self._episode_urls = self._scrape_episodes()
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\anime_downloader\sites\gogoanime.py", line 82, in _scrape_episodes
    anime_id = soup.select_one('input#movie_id').attrs['value']
AttributeError: 'NoneType' object has no attribute 'attrs'

```

**Comment by Blatzar** [comment] 2020-08-30 12:28
Gogoanime is written for https://gogoanime.io, but that seems to be down so might be best to switch to gogoanime.app

**Comment by ArjixGamer** [comment] 2020-08-30 12:29
down?

**Comment by phanirithvij** [comment] 2020-08-30 12:29
https://gogoanime.life/

**Comment by ArjixGamer** [comment] 2020-08-30 12:30
gogoanime.io works fine

**Comment by ArjixGamer** [comment] 2020-08-30 12:30
no, gogoanime.io / gogoanime.tv / gogoanime.video
those are the true mirrors

**Comment by Blatzar** [comment] 2020-08-30 12:31
@ArjixGamer seeems to be an issue for me then 
![image](https://user-images.githubusercontent.com/46196380/91659045-63190200-eacd-11ea-98bd-f45ee38379a4.png)

**Comment by ArjixGamer** [comment] 2020-08-30 12:31
loads perfectly fine for me

**Comment by phanirithvij** [comment] 2020-08-30 12:31
So close this?

**Comment by ArjixGamer** [comment] 2020-08-30 12:31
oh, lagrad, you dont get the redirects

**Comment by ArjixGamer** [comment] 2020-08-30 12:32
gogoanime.movie is the new temp domain

**Comment by ArjixGamer** [comment] 2020-08-30 12:33
yeah. close it

**Comment by phanirithvij** [comment] 2020-08-30 12:33
Hmm, weird. `anime dl "https://www1.gogoanime.movie/category/gintama-kanketsu-hen-yorozuya-yo-eien-nare"` gives the mp4 file as an m3u8 file.
```
λ cat Gintama_Kanketsu-hen__Yorozuya_yo_Eien_Nare_1.mp4
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=312378,RESOLUTION=640x360,NAME="360p"
sub.1.360.m3u8
```

**Comment by Blatzar** [comment] 2020-08-30 12:34
Leave it open, the gogoanime script seems to fail on multiple different clones. Arjix can you confirm if anime dl "gintama" -p gogoanime still works for you?

**Comment by ArjixGamer** [comment] 2020-08-30 12:35
yep, it downloads an mp4 too

**Comment by phanirithvij** [comment] 2020-08-30 12:35
```
λ anime dl "gintama" -p gogoanime
anime: anime-downloader 4.6.3
+--------+-----------------------------------------------+--------+
|     12 | Gintama: Kanketsu-hen – Yorozuya yo Eien Nare |        |
|     11 | Gintama: Shinyaku Benizakura-hen (Dub)        |        |
|     10 | Gintama.: Shirogane no Tamashii-hen 2         |        |
|      9 | Gintama.: Shirogane no Tamashii-hen           |        |
|      8 | Gintama: Shinyaku Benizakura Hen              |        |
|      7 | Gintama: Aizome Kaori-hen                     |        |
|      6 | Gintama: Jump Festa 2015                      |        |
|      5 | Gintama' (2015)                               |        |
|      4 | Gintama. (2017)                               |        |
|      3 | Gintama (2017)                                |        |
|      2 | Gintama OVA                                   |        |
|      1 | Gintama                                       |        |
|--------+-----------------------------------------------+--------|
|   SlNo | Title                                         | Meta   |
+--------+-----------------------------------------------+--------+
Enter the anime no: [1]: 12
anime: Selected Gintama: Kanketsu-hen – Yorozuya yo Eien Nare
anime: Extracting episode info from page
anime: Found anime: Gintama: Kanketsu-hen – Yorozuya yo Eien Nare
anime: Downloading to D:\Videos\ANIME\gintama\Gintama_Kanketsu-hen__Yorozuya_yo_Eien_Nare
anime: Downloading Gintama: Kanketsu-hen – Yorozuya yo Eien Nare-1
anime: .\Gintama_Kanketsu-hen__Yorozuya_yo_Eien_Nare/Gintama_Kanketsu-hen__Yorozuya_yo_Eien_Nare_1.mp4
anime: Using internal downloader which might be slow. Use aria2 for full bandwidth.
Downloaded: 0.02MB/0.00MB, Rate: 8.44KB/s
```

**Comment by ArjixGamer** [comment] 2020-08-30 12:36
link i got for ep 1: https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

**Comment by ArjixGamer** [comment] 2020-08-30 12:37
```
C:\Users\arjix>anime dl "gintama" -p gogoanime
anime: anime-downloader 4.6.3
+--------+-----------------------------------------------+--------+
|     12 | Gintama: Kanketsu-hen – Yorozuya yo Eien Nare |        |
|     11 | Gintama: Shinyaku Benizakura-hen (Dub)        |        |
|     10 | Gintama.: Shirogane no Tamashii-hen 2         |        |
|      9 | Gintama.: Shirogane no Tamashii-hen           |        |
|      8 | Gintama: Shinyaku Benizakura Hen              |        |
|      7 | Gintama: Aizome Kaori-hen                     |        |
|      6 | Gintama: Jump Festa 2015                      |        |
|      5 | Gintama' (2015)                               |        |
|      4 | Gintama. (2017)                               |        |
|      3 | Gintama (2017)                                |        |
|      2 | Gintama OVA                                   |        |
|      1 | Gintama                                       |        |
|--------+-----------------------------------------------+--------|
|   SlNo | Title                                         | Meta   |
+--------+-----------------------------------------------+--------+
Enter the anime no: [1]:
anime: Selected Gintama
anime: Extracting episode info from page
anime: Found anime: Gintama
anime: Downloading to H:\Anime

08/30 15:35:17 [NOTICE] Downloading 1 item(s)

08/30 15:35:17 [NOTICE] CUID#7 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.

08/30 15:35:18 [NOTICE] CUID#9 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#12 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#13 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#15 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#19 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#11 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#10 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#14 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#16 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#17 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#18 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4
[#3d8948 496KiB/136MiB(0%) CN:12 DL:1.8MiB ETA:1m13s]
08/30 15:35:18 [NOTICE] CUID#15 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#19 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#17 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4

08/30 15:35:18 [NOTICE] CUID#16 - Redirecting to https://storage.googleapis.com/amazing-smile-287316/MJRAAVHX4582/23a_1598599068_17075.mp4
[#3d8948 2.5MiB/136MiB(1%) CN:12 DL:2.0MiB ETA:1m4s]
```

**Comment by phanirithvij** [comment] 2020-08-30 12:37
Could you try for the [12]: Gintama: Kanketsu-hen – Yorozuya yo Eien Nar

**Comment by ArjixGamer** [comment] 2020-08-30 12:39
hmm, i think it gets an m3u8

**Comment by phanirithvij** [comment] 2020-08-30 12:40
How to choose a different server via cli?

**Comment by dausruddin** [comment] 2020-09-08 03:00
I can confirm that it downloads m3u files instead of a video.

Command: `https://www1.gogoanime.movie/category/gekitou-crush-gear-turbo-dub`

```
$ cat Gekitou_Crush_Gear_Turbo_Dub_01.mp4 
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=377969,RESOLUTION=466x360,NAME="360p"
dub.1.360.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=489260,RESOLUTION=622x480,NAME="480p"
dub.1.480.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1174803,RESOLUTION=932x720,NAME="720p"
dub.1.720.m3u8
```

**Comment by Blatzar** [comment] 2020-09-19 22:46
Gogoanime removed in favor of vidstream

**Closed by Blatzar** 2020-09-19 22:46 UTC
