### ISSUE TITLE
There's something wrong with Rapidvideo

### ISSUE THREAD

**Issue by phanirithvij** [vn-ki/anime-downloader#56] opened 2018-07-28 20:09 UTC
## Feature request

Rapidvideo refuses to connect when I try using my usual internet connection
They are blocking my IP address and It happened after I started downloading a lot of videos from rapidvideo.(I think that might be a logical reason but It doesn't make sense because It's no different from iframe in 9anime or kissanime)
I don't know why they'd do that to a random user.

I can't use 9anime and kissanime through anime_downloader but I can use it for twist.moe and others which don't entirely rely on rapidvideo so I thought extending 9anime by a source like openload as kissanime has image capcha thing.

I know it's a selfish request and I can just revert it by changing my network provider or some tor browser or a proxy

## Please think about adding openload extractor.

**Comment by phanirithvij** [comment] 2018-07-28 20:11
Oh and translate.google.com is a proxy
I forgot to mention about It

**Comment by vn-ki** [comment] 2018-07-31 17:49
Duplicate of #32. As I mentioned there, it's not quite straightforward. I will get back to it in sometime. Lots of things going around me now.

**Closed by vn-ki** 2018-07-31 17:49 UTC
