### ISSUE TITLE
9anime: Invalid JSON (which is actually not true)

### ISSUE THREAD

**Issue by IngwiePhoenix** [vn-ki/anime-downloader#181] opened 2019-05-02 20:01 UTC
**Describe the bug**
As of yesterday evening, 9anime does no longer work. I suppose they changed some of their APIs, and this is affecting this downloader - however, the fix is easy.

Apparently, all that is required is to follow the 301 location and the proper JSON appears :)

To reproduce the actual and proper result, use `-ll DEBUG` and follow the failing URL with cURL. This is attached below as well.

**To reproduce**
Just run `anime dl` on any 9anime URL.

<details>
<summary>LOG</summary>

```
$ anime dl "https://www4.9anime.to/watch/hanaukyo-maid-team-la-verite-dub.09n9/2ym4j5" -ll DEBUG
INFO root: anime-downloader 3.6.3
DEBUG root: Platform: Linux-4.15.0-48-generic-x86_64-with-Ubuntu-18.04-bionic
DEBUG root: Python 3.6.7
INFO root: Extracting episode info from page
DEBUG root: data-ts: 1556780400
DEBUG root: EPISODE IDS: length: 12, ids: ['f40bc56a787f69dc53842f9c1eeba28decc74e6e2ccee04008d19b7b0e6518ee', '37d9bd2da67e0daa18a079bb085d7fa279a6a8a95e33b898c4f0a31a5cd44374', '94d3dcb0420da9e9ca62b0409cd5b2da67bbfc04a237943e2254e884b3d36844', 'bbbfef4c14725785b82878883d08a991e712d7c0bb2946b187af5d1b6e1812dd', '92333caffa15e7d3d46f53f5e398692de6b1185a3c6da42b928968ffb8bc1e3d', '2aec8408959f78bd90f45c2f838952d33dbbf07233b66fce29ff7a42eb201838', '586cf0008a4fbe4806a1aecbc5405c97b6739485d07ff8c8b6273ce0152bbedd', '3c3cd54cd29de602597fcee5867e39e60928c3c431fbefd894b80515fb7cc6ab', '8eac0fe36f569417d80e629f3f85687f5185496f644ca7eae90629a7ede85aaf', 'fc81b2c845f7d4b200a32632bbb392f08aa4d5105a3fec24712452a84ffab7dd', '8c5af450bc1ba5eb163b5c3d0ee67523534f96c7e899af15bddc1de391a8759b', '6d7bfa30ec4bcd94c0b409b26b1145a4ef45f222178a1c2de488efb7345cf212']
INFO root: Found anime: Hanaukyo Maid Team: La Verite (Dub)
INFO root: Downloading to /home/ingwie/anime
DEBUG root: Extracting stream info of id: f40bc56a787f69dc53842f9c1eeba28decc74e6e2ccee04008d19b7b0e6518ee
DEBUG root: API call URL: https://9anime.to/ajax/episode/info with params {'id': 'f40bc56a787f69dc53842f9c1eeba28decc74e6e2ccee04008d19b7b0e6518ee', 'server': '33', 'ts': '1556780400', '_': 744}
DEBUG root: URL: https://9anime.to/ajax/episode/info?id=f40bc56a787f69dc53842f9c1eeba28decc74e6e2ccee04008d19b7b0e6518ee&server=33&ts=1556780400&_=744
Traceback (most recent call last):
  File "/home/ingwie/.local/bin/anime", line 10, in <module>
    sys.exit(cli())
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/anime_downloader/cli.py", line 127, in dl
    for episode in animes:
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 78, in __getitem__
    ep_no=ep_id[0])
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 122, in __init__
    self.get_data()
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 162, in get_data
    self._sources = self._get_sources()
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/anime_downloader/sites/nineanime.py", line 35, in _get_sources
    url = get_stream_url(self._base_url, params)
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/anime_downloader/sites/nineanime.py", line 30, in get_stream_url
    data = util.get_json(base_url, params=params)
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/anime_downloader/util.py", line 153, in get_json
    data = res.json()
  File "/home/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
```
$ curl -vL "https://9anime.to/ajax/episode/info?id=f40bc56a787f69dc53842f9c1eeba28decc74e6e2ccee04008d19b7b0e6518ee&server=33&ts=1556780400&_=744"
*   Trying 2606:4700:30::6812:28ea...
* TCP_NODELAY set
* Connected to 9anime.to (2606:4700:30::6812:28ea) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=sni.cloudflaressl.com
*  start date: Dec 19 00:00:00 2018 GMT
*  expire date: Dec 19 12:00:00 2019 GMT
*  subjectAltName: host "9anime.to" matched cert's "9anime.to"
*  issuer: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=CloudFlare Inc ECC CA-2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55e145896780)
> GET /ajax/episode/info?id=f40bc56a787f69dc53842f9c1eeba28decc74e6e2ccee04008d19b7b0e6518ee&server=33&ts=1556780400&_=744 HTTP/2
> Host: 9anime.to
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 301 
< date: Thu, 02 May 2019 20:01:05 GMT
< content-type: text/html
< content-length: 178
< set-cookie: __cfduid=d0f5393f8a9f6255f24de77754421e7e11556827265; expires=Fri, 01-May-20 20:01:05 GMT; path=/; domain=.9anime.to; HttpOnly
< location: https://www4.9anime.to/ajax/episode/info?id=f40bc56a787f69dc53842f9c1eeba28decc74e6e2ccee04008d19b7b0e6518ee&server=33&ts=1556780400&_=744
< ucs: m1
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 4d0c95c8acd697c0-FRA
< 
* Ignoring the response-body
* Connection #0 to host 9anime.to left intact
* Issue another request to this URL: 'https://www4.9anime.to/ajax/episode/info?id=f40bc56a787f69dc53842f9c1eeba28decc74e6e2ccee04008d19b7b0e6518ee&server=33&ts=1556780400&_=744'
*   Trying 2606:4700:30::6812:28ea...
* TCP_NODELAY set
* Connected to www4.9anime.to (2606:4700:30::6812:28ea) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=sni.cloudflaressl.com
*  start date: Dec 19 00:00:00 2018 GMT
*  expire date: Dec 19 12:00:00 2019 GMT
*  subjectAltName: host "www4.9anime.to" matched cert's "*.9anime.to"
*  issuer: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=CloudFlare Inc ECC CA-2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55e145896780)
> GET /ajax/episode/info?id=f40bc56a787f69dc53842f9c1eeba28decc74e6e2ccee04008d19b7b0e6518ee&server=33&ts=1556780400&_=744 HTTP/2
> Host: www4.9anime.to
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Thu, 02 May 2019 20:01:05 GMT
< content-type: application/json
< set-cookie: __cfduid=d963c821b13ef660d86f810a61a938ba01556827265; expires=Fri, 01-May-20 20:01:05 GMT; path=/; domain=.9anime.to; HttpOnly
< access-control-allow-credentials: true
< access-control-allow-origin: https://www4.9anime.to
< x-bl: 0.0
< ucs: m1
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 4d0c95ca3dab969e-FRA
< 
* Connection #1 to host www4.9anime.to left intact
{"grabber":"","params":[],"backup":0,"target":"https:\/\/www.rapidvideo.com\/e\/FWVSQVJDCK","type":"iframe","name":"01","subtitle":""}
```
</details>

**Comment by miasmaejuices** [comment] 2019-05-03 15:54
For reference, this is probably a similar older issue to https://github.com/vn-ki/anime-downloader/issues/21

@vn-ki may be able to fix it up faster than me, but I'll have a look as well.  If I come up with a fix, I'll note it.

**Comment by IngwiePhoenix** [comment] 2019-05-03 18:06
I tried to track the HTTP calls down in order to see where the follow-locations option was (-L for cURL). That is really the only thing that needs to be done to fix this :)

**Comment by vn-ki** [comment] 2019-05-08 18:36
The problem is captcha, not http redirection. Requests should handle any kind of redirection.

Closing as the discussion is on #183

**Closed by vn-ki** 2019-05-08 18:36 UTC
