### ISSUE TITLE
ERROR: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by Itadakimashu** [vn-ki/anime-downloader#380] opened 2020-05-30 15:32 UTC
When I try to download via animepahe provider it gets this kind of message no attribute 'groups'

**Comment by Blatzar** [comment] 2020-05-30 15:33
We can not solve this issue with only that information. Please post full debug logs, eg. `anime -ll DEBUG dl "vinland saga"` for example.

**Comment by ArjixGamer** [comment] 2020-05-30 15:41
possibly a duplicate of: [#374](https://github.com/vn-ki/anime-downloader/issues/374)

**Comment by ArjixGamer** [comment] 2020-05-30 15:42
please check if the issue is already reported before making a new one.
That would allow us to focus on other issues too.

**Comment by Blatzar** [comment] 2020-05-30 15:43
> possibly a duplicate of: [#374](https://github.com/vn-ki/anime-downloader/issues/374)

No, that's a whole different issue. It's a duplicate of https://github.com/vn-ki/anime-downloader/issues/375

**Comment by ArjixGamer** [comment] 2020-05-30 15:44
they both have an error similar if not identical to this:
`AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by AbdullahM0hamed** [comment] 2020-05-30 15:54
@ArjixGamer having the same error being thrown by different providers, would not cause the issues to be the same - as they would have different code, and they would be entirely unrelated to each other.

Having the same error on the same provider, however, would cause the issues to be the same. 

Thus, this is a duplicate of #375 and not #374.

**Comment by MichaelDavidJohnson** [comment] 2020-05-31 16:21
Can we please close issues that are done with.

**Closed** 2020-05-31 16:22 UTC
