### ISSUE TITLE
errorCode 19

### ISSUE THREAD

**Issue by johnpyp** [vn-ki/anime-downloader#47] opened 2018-07-14 21:09 UTC
**Describe the bug**

After downloading more than 70 episodes of an Anime,it suddenly started giving me this error:
```
anime: Downloading episode 112 of Fairy Tail (Sub)

07/14 16:57:19 [NOTICE] Downloading 1 item(s)

07/14 16:57:19 [ERROR] CUID#7 - Download aborted. URI=https://www506.playercdn.net/173/0/YQP6zD5DBZMiOYTFngdJVw/1531623439/170427/6iXPJXswijp2FOR.mp4
Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://www506.playercdn.net/173/0/YQP6zD5DBZMiOYTFngdJVw/1531623439/170427/6iXPJXswijp2FOR.mp4
  -> [AbstractCommand.cc:792] errorCode=19 CUID#7 - Name resolution for www506.playercdn.net failed:Domain name not found

07/14 16:57:19 [NOTICE] Download GID#aa6433af9f705a65 not complete: /media/johnpyp/sdb3/tv/Fairy_Tail/Fairy Tail - s01e112.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
aa6433|ERR |       0B/s|/media/johnpyp/sdb3/tv/Fairy_Tail/Fairy Tail - s01e112.mp4

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

```
And in turn stopping the process.

Now I might be able to download 3-4 episodes before it stops working again.
**To reproduce**
```
anime dl -e 1:175 'http://kissanime.ru/Anime/Fairy-Tail' -xd "{aria2}" -q 360p --provider kissanime --download-dir ./Fairy_Tail -ff "Fairy Tail - s01e{ep_no}"

```
Same issue when searching rather than using a direct url.

<details>
<summary>LOG</summary>

```
$ anime dl -e 112:175 'http://kissanime.ru/Anime/Fairy-Tail' -xd "{aria2}" -q 360p --provider kissanime --download-dir ./Fairy_Tail -ff "Fairy Tail - s01e{ep_no}" --log-level DEBUG
INFO root: anime-downloader 3.2.0
DEBUG root: Platform: Linux-4.15.0-24-generic-x86_64-with-Ubuntu-18.04-bionic
DEBUG root: Python 3.6.5
INFO root: Extracting episode info from page
DEBUG root: Unfiltered episodes : ['http://kissanime.ru/Anime/Fairy-Tail/Episode-175?id=26397', 'http://kissanime.ru/Anime/Fairy-Tail/Episode-174?id=25364', 'http://kissanime.ru/Anime/Fairy-Tail/Episode-173?id=24123',
// Long list of episodes
'http://kissanime.ru/Anime/Fairy-Tail/Episode-001?id=816']
DEBUG root: Filtered episodes : ['http://kissanime.ru/Anime/Fairy-Tail/Episode-175?',
// Long list of episodes
'http://kissanime.ru/Anime/Fairy-Tail/Episode-001?id=816']
DEBUG root: EPISODE IDS: length: 175, ids: ['http://kissanime.ru/Anime/Fairy-Tail/Episode-001?id=816', 'http://kissanime.ru/Anime/Fairy-Tail/Episode-002?id=817', 'http://kissanime.ru/Anime/Fairy-Tail/Episode-003?id=818', 'http://kissanime.ru/Anime/Fairy-Tail/Episode-004?id=819', 
// Long list of episodes
'http://kissanime.ru/Anime/Fairy-Tail/Episode-175?id=26397']
INFO root: Found anime: Fairy Tail (Sub)
INFO root: Downloading to /media/johnpyp/sdb3/tv/Fairy_Tail
DEBUG root: Extracting stream info of id: http://kissanime.ru/Anime/Fairy-Tail/Episode-112?id=734
DEBUG root: Calling url: http://kissanime.ru/Anime/Fairy-Tail/Episode-112?id=734&s=rapidvideo
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FF2TV2UHL7&q=360p
INFO root: Downloading episode 112 of Fairy Tail (Sub)
DEBUG root: cmd: {aria2}
DEBUG root: episode: <anime_downloader.sites.kissanime.KissanimeEpisode object at 0x7f04bfe76e10>
DEBUG root: file format: Fairy Tail - s01e{ep_no}
DEBUG root: formatted cmd: aria2c https://www506.playercdn.net/173/0/304GNCnncWrO-6BohJ82yw/1531623911/170427/6iXPJXswijp2FOR.mp4 -x 12 -s 12 -j 12 -k 10M -o Fairy Tail - s01e112.mp4 --continue=true --dir=/media/johnpyp/sdb3/tv/Fairy_Tail --stream-piece-selector=inorder --min-split-size=5M

07/14 17:05:12 [NOTICE] Downloading 1 item(s)

07/14 17:05:12 [ERROR] CUID#7 - Download aborted. URI=https://www506.playercdn.net/173/0/304GNCnncWrO-6BohJ82yw/1531623911/170427/6iXPJXswijp2FOR.mp4
Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://www506.playercdn.net/173/0/304GNCnncWrO-6BohJ82yw/1531623911/170427/6iXPJXswijp2FOR.mp4
  -> [AbstractCommand.cc:792] errorCode=19 CUID#7 - Name resolution for www506.playercdn.net failed:Domain name not found

07/14 17:05:12 [NOTICE] Download GID#ab7fc31b72737590 not complete: /media/johnpyp/sdb3/tv/Fairy_Tail/Fairy Tail - s01e112.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
ab7fc3|ERR |        n/a|/media/johnpyp/sdb3/tv/Fairy_Tail/Fairy Tail - s01e112.mp4

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
```
</details>

**Comment by vn-ki** [comment] 2018-07-14 21:19
I have never encountered this. If I had to guess, I would say it is rapidvideo blocking your requests. I had this happen with the CI servers and I have not found a workaround yet.

**Comment by johnpyp** [comment] 2018-07-14 21:29
Is there any way to use one of the other servers? I don't want to use 9anime because they use different subs.

**Comment by vn-ki** [comment] 2018-07-14 21:35
You can use masterani if you want. My ISP blocks(?) openload and streamango, so I could not develop stream url extractors for them. In a few weeks, I would be able to do that.

> Is there any way to use one of the other servers? 

If you are talking about KA servers other than rapidvideo, then no. They use image captcha which is not easy to fool.

Also, did you try the stream url through your browser?

**Comment by johnpyp** [comment] 2018-07-14 21:46
In browser I get the native "This site can’t be reached", not like an nginx 404.

I'll try masterani, thanks.

**Comment by johnpyp** [comment] 2018-07-14 21:49
--provider for masterani isn't working

**Comment by vn-ki** [comment] 2018-07-14 21:54
> --provider for masterani isn't working

You have to provide the full link. I have not implemented search for masterani yet. Kinda busy nowadays. Also for your KA problem, maybe a restart might help.

**Comment by johnpyp** [comment] 2018-07-14 21:55
Oh ok, thanks

**Comment by johnpyp** [comment] 2018-07-14 21:58
I'll try kissanime some more, but it seems Masterani isn't working:
```
johnpyp@johnpyp:/media/johnpyp/sdb3/tv$ anime dl 'https://www.masterani.me/anime/info/257-fairy-tail' -xd "{aria2}"  -ff "Fairy Tail - s01e{ep_no}"
anime: anime-downloader 3.2.0
anime: Extracting episode info from page
anime: Found anime: Fairy Tail
anime: Downloading to /media/johnpyp/sdb3/tv
```
It just stops at that.

**Comment by vn-ki** [comment] 2018-07-14 22:04
Yeah. I can reproduce it.

Looks like this anime has only streamango and mp4upload sources. Weird.

As I said I cannot access streamango and mp4upload uses js obfuscation (packer, if my memory serves me right). I could reverse mp4upload, but I'm not in the mood rn :sweat_smile:.

So yeah, you're better off with KA. (But 9A would be the most reliable)

**Comment by johnpyp** [comment] 2018-07-14 22:07
No worries, I'm trying 9A right now. Noticed some inconsistencies in the subs, but it probably isn't that big of a deal. Thanks for this, I was in the middle of building a scraper in node js, but I decided to do some more extensive research and I found the first one that works!

**Comment by vn-ki** [comment] 2018-07-14 22:11
I should've used node instead of python. I have to translate uglified js to python because I went the python way. Anyway this works for now.

Happy that you're enjoying it. Closing this issue now.

**Closed by vn-ki** 2018-07-14 22:11 UTC

**Comment by vn-ki** [comment] 2018-07-14 22:12
Oh yeah. Update your installation before trying 9anime. I have released a new version.

**Comment by johnpyp** [comment] 2018-07-14 22:17
Damn went from 500-1000kib to like 10mb download, does that token change have a big effect?

**Comment by vn-ki** [comment] 2018-07-14 22:20
9anime is very scraper unfriendly. They change their tokens every now and then. So I have a fallback mechanism in place (falls back to 9anime.cloud). I don't know how it can affect the speed though.

**Comment by johnpyp** [comment] 2018-07-14 22:20
Gotcha
