### ISSUE TITLE
Can some help me with this bug

### ISSUE THREAD

**Issue by bibek011** [vn-ki/anime-downloader#101] opened 2018-10-28 13:13 UTC
**Describe the bug**
I don't exactly know what this bug is but i cannot download any anime at all tried using different sites like kissanime, animepahe etc.

I am using the latest version of anime downloader 3.6.0. i was able to download anime perfectly fine from kissanime on version 3.5.0

**To reproduce**

anime dl http://kissanime.ru/Anime/High-School-DxD-Hero

<details>
<summary>LOG</summary>
anime: Found anime: High School DxD 4th Season (Sub)
anime: Downloading to D:\Movies\Anime\Downloaded\
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python37\Scripts\anime-script.py", line 11, in <module>
    load_entry_point('anime-downloader==3.6.0', 'console_scripts', 'anime')()

  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\cli.py", line 135, in dl
    episode.ep_no, anime.title)
AttributeError: 'list' object has no attribute 'title'
</details>

**Comment by vn-ki** [comment] 2018-10-28 18:43
I cannot reproduce this. Can you try again? Nothing important has been changed in kissanime.py from 3.5 to 3.6.

What did you try with other providers?

**Comment by bibek011** [comment] 2018-10-30 17:52
> I cannot reproduce this. Can you try again? Nothing important has been changed in kissanime.py from 3.5 to 3.6.
> 
> What did you try with other providers?

it is still occuring for me.. i tried using animepahe (mp4upload) and kissanime (rapidvideo)

**Comment by bibek011** [comment] 2018-10-31 09:35
> Please post the log for kissanime.

Here is the log for kissanime
Command used: anime dl http://kissanime.ru/Anime/High-School-DxD-Hero --provider kissanime --episodes 06:12

`C:\Users\Acer>anime dl http://kissanime.ru/Anime/High-School-DxD-Hero --provider kissanime --episodes 06:12
[32manime[0m: anime-downloader 3.6.1
[32manime[0m: Extracting episode info from page
anime: Found anime: High School DxD 4th Season (Sub)
anime: Downloading to D:\Movies\Anime\Downloaded\
Traceback (most recent call last):
  File "c:\users\acer\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\acer\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python37\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\acer\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\cli.py", line 135, in dl
    episode.ep_no, anime.title)
AttributeError: 'list' object has no attribute 'title'`

**Comment by vn-ki** [comment] 2018-11-04 07:34
Try deleting config file located here `C:\Users\[Username]\AppData\Roaming\anime downloader`. @Jtgroos

**Comment by bibek011** [comment] 2018-11-17 10:30
has anyone found a fix yet??

**Comment by mcj64** [comment] 2018-11-19 22:16
I think the problem can be solved in line 117 and line 125 of cli.py by changing the variable name of 'anime' as line 117 redefine variable 'anime' and cause 'anime.title' to not exist anymore. I have never learnt python programming before this but I sort of play with the code and it worked.

**Comment by bibek011** [comment] 2018-12-21 09:10
> this should be fixed in #110

Thanks for the solution.

**Comment by vn-ki** [comment] 2018-12-24 12:01
Should be fixed in 3.6.2

**Closed by vn-ki** 2018-12-24 12:01 UTC
