### ISSUE TITLE
The quality selection doesn't work

### ISSUE THREAD

**Issue by Altair-python** [vn-ki/anime-downloader#340] opened 2020-04-12 13:28 UTC
**Describe the bug**

The selection of quality doesn't work. it always downloads the anime eps in 1080p resolution

**To reproduce**

```
anime dl --log-level DEBUG "sword art online" -q "720p" -xd "{aria2}"
```

<details>
<summary>
2020-04-12 18:50:36 SHASIDHARAN-PC anime_downloader.util[3524] INFO anime-downloader 4.2.0
2020-04-12 18:50:36 SHASIDHARAN-PC anime_downloader.util[3524] DEBUG Platform: Windows-7-6.1.7601-SP1
2020-04-12 18:50:36 SHASIDHARAN-PC anime_downloader.util[3524] DEBUG Python 3.7.7
2020-04-12 18:50:37 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG HTML file temp_dir: C:\Users\Arjun\AppData\Local\Temp\animedlyro06o09
2020-04-12 18:50:37 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG -----
2020-04-12 18:50:37 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG GET https://twist.moe/api/anime
2020-04-12 18:50:37 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG {}
2020-04-12 18:50:37 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.46 Safari/537.36', 'x-access-token': '1rj2vRtegS8Y60B3w3qNZm5T2Q0TN2NR'}
2020-04-12 18:50:37 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG -----
send: b'GET /api/anime HTTP/1.1\r\nHost: twist.moe\r\nuser-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.46 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nx-access-token: 1rj2vRtegS8Y60B3w3qNZm5T2Q0TN2NR\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: Sucuri/Cloudproxy
header: Date: Sun, 12 Apr 2020 13:20:36 GMT
header: Content-Type: application/json; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: X-Sucuri-ID: 15011
header: Vary: Accept-Encoding
header: Access-Control-Allow-Origin: *
header: Access-Control-Allow-Methods: GET,HEAD,PUT,POST,DELETE,PATCH
header: Content-Encoding: gzip
header: Strict-Transport-Security: max-age=15768000
header: X-Frame-Options: SAMEORIGIN
header: X-Content-Type-Options: nosniff
header: X-Sucuri-Cache: BYPASS
2020-04-12 18:50:38 SHASIDHARAN-PC anime_downloader.session[3524] DEBUG uncached request
2020-04-12 18:50:38 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG https://twist.moe/api/anime
2020-04-12 18:50:38 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG C:\Users\Arjun\AppData\Local\Temp\animedlyro06o09\tmpkmif7mjl
+--------+-----------------------------------------------+--------+
|      5 | Sword Art Online: Alicization                 |        |
|      4 | Sword Art Online: Alternative Gun Gale Online |        |
|      3 | Sword Art Online Movie: Ordinal Scale         |        |
|      2 | Sword Art Online II                           |        |
|      1 | Sword Art Online                              |        |
|--------+-----------------------------------------------+--------|
|   SlNo | Title                                         | Meta   |
+--------+-----------------------------------------------+--------+
Enter the anime no:  [1]: 2
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.util[3524] INFO Selected Sword Art Online II
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.sites.anime[3524] INFO Extracting episode info from page
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG -----
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG GET https://twist.moe/api/anime/sword-art-online-ii/sources
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG {}
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.46 Safari/537.36', 'x-access-token': '1rj2vRtegS8Y60B3w3qNZm5T2Q0TN2NR'}
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG -----
send: b'GET /api/anime/sword-art-online-ii/sources HTTP/1.1\r\nHost: twist.moe\r\nuser-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.46 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nx-access-token: 1rj2vRtegS8Y60B3w3qNZm5T2Q0TN2NR\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: Sucuri/Cloudproxy
header: Date: Sun, 12 Apr 2020 13:20:46 GMT
header: Content-Type: application/json; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: X-Sucuri-ID: 15011
header: Vary: Accept-Encoding
header: Access-Control-Allow-Origin: *
header: Access-Control-Allow-Methods: GET,HEAD,PUT,POST,DELETE,PATCH
header: Content-Encoding: gzip
header: Strict-Transport-Security: max-age=15768000
header: X-Frame-Options: SAMEORIGIN
header: X-Content-Type-Options: nosniff
header: X-Sucuri-Cache: BYPASS
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.session[3524] DEBUG uncached request
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG https://twist.moe/api/anime/sword-art-online-ii/sources
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.sites.helpers.request[3524] DEBUG C:\Users\Arjun\AppData\Local\Temp\animedlyro06o09\tmpr6nxisak
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.commands.dl[3524] INFO Found anime: sword-art-online-ii
INFO:anime_downloader.commands.dl:Found anime: sword-art-online-ii
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.commands.dl[3524] INFO Downloading to H:\anime\SAO
INFO:anime_downloader.commands.dl:Downloading to H:\anime\SAO
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.sites.anime[3524] DEBUG Extracting stream info of id: https://twist.moe/anime/swordartonlines2/[HorribleSubs] Sword Art Online II - 01 [1080p].mp4
DEBUG:anime_downloader.sites.anime:Extracting stream info of id: https://twist.moe/anime/swordartonlines2/[HorribleSubs] Sword Art Online II - 01 [1080p].mp4
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.sites.anime[3524] DEBUG Sources : [('no_extractor', 'https://twist.moe/anime/swordartonlines2/[HorribleSubs] Sword Art Online II - 01 [1080p].mp4')]
DEBUG:anime_downloader.sites.anime:Sources : [('no_extractor', 'https://twist.moe/anime/swordartonlines2/[HorribleSubs] Sword Art Online II - 01 [1080p].mp4')]
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.util[3524] DEBUG cmd: {aria2}
DEBUG:anime_downloader.util:cmd: {aria2}
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.util[3524] DEBUG episode: <anime_downloader.sites.twistmoe.TwistMoeEpisode object at 0x0000000004362CC8>
DEBUG:anime_downloader.util:episode: <anime_downloader.sites.twistmoe.TwistMoeEpisode object at 0x0000000004362CC8>
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.util[3524] DEBUG file format: {anime_title}/{ep_no}
DEBUG:anime_downloader.util:file format: {anime_title}/{ep_no}
2020-04-12 18:50:47 SHASIDHARAN-PC anime_downloader.util[3524] DEBUG formatted cmd: aria2c https://twist.moe/anime/swordartonlines2/[HorribleSubs] Sword Art Online II - 01 [1080p].mp4 -x 12 -s 12 -j 12 -k 10M -o sword-art-online-ii/01.mp4 --continue=true --dir=H:\anime\SAO --stream-piece-selector=inorder --min-split-size=5M --referer=https://twist.moe/anime/swordartonlines2/[HorribleSubs] Sword Ar
t Online II - 01 [1080p].mp4 --check-certificate=false --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
DEBUG:anime_downloader.util:formatted cmd: aria2c https://twist.moe/anime/swordartonlines2/[HorribleSubs] Sword Art Online II - 01 [1080p].mp4 -x 12 -s 12 -j 12 -k 10M -o sword-art-online-ii/01.mp4 --continue=true --dir=H:\anime\SAO --stream-piece-selector=inorder --min-split-size=5M --referer=https://twist.moe/anime/swordartonlines2/[HorribleSubs] Sword Art Online II - 01 [1080p].mp4 --check-cert
ificate=false --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36

04/12 18:50:48 [NOTICE] Downloading 1 item(s)

04/12 18:50:48 [NOTICE] CUID#7 - Redirecting to https://twistcdn.bunny.sh/anime/swordartonlines2/[HorribleSubs]%20Sword%20Art%20Online%20II%20-%2001%20[1080p].mp4
[#fd026f 0B/0B CN:1 DL:0B]
04/12 18:50:49 [NOTICE] CUID#7 - Redirecting to https://edge-7.cdn.bunny.sh/anime/swordartonlines2/[HorribleSubs]%20Sword%20Art%20Online%20II%20-%2001%20[1080p].mp4
[#fd026f 0B/0B CN:1 DL:0B]
04/12 18:50:51 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.

04/12 18:50:51 [NOTICE] Shutdown sequence commencing... Press Ctrl-C again for emergency shutdown.

04/12 18:50:51 [NOTICE] Download GID#fd026f91912e765d not complete: H:/anime/SAO/sword-art-online-ii/01.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
fd026f|INPR|       0B/s|H:/anime/SAO/sword-art-online-ii/01.mp4
</summary>

```



```

**Comment by Blatzar** [comment] 2020-04-12 13:35
Quality selection isn't available on all sites. Not a bug, it's impossible to add quality selection if the site only hosts one file.

**Comment by Altair-python** [comment] 2020-04-12 13:48
> Quality selection isn't available on all sites. Not a bug, it's impossible to add quality selection if the site only hosts one file.

ohh then let me know the sites which supports

**Comment by Blatzar** [comment] 2020-04-12 18:24
Looking at the code it looks like:
erairaws: 720p and 1080p
providers which use gcloud: watchmovie and animekisa. All qualities are supported (in the code), seems like they mostly use 720p and 1080p.
providers which use rapidvideo: 9anime, gogoanime and kissanime. Haven't worked with them myself so can't confirm how well that works.

**Comment by Blatzar** [comment] 2020-04-16 19:56
Closing this as it's nothing which can be fixed.

**Closed by Blatzar** 2020-04-16 19:56 UTC
