### ISSUE TITLE
'html' Error when trying to downloader

### ISSUE THREAD

**Issue by ComatoseCow** [vn-ki/anime-downloader#82] opened 2018-09-26 00:13 UTC
**Describe the bug**

When I try to run the anime dl command I get an error 'html'.

**To reproduce**

```
anime dl 'overlord'
```

<details>
<summary>LOG</summary>
```

Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/cli.py", line 99, in dl
    fallback_qualities=fallback_qualities)
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/anime.py", line 42, in __init__
    self.get_data()
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/anime.py", line 60, in get_data
    self._episode_urls = self._scarpe_episodes(soup)
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/nineanime.py", line 112, in _scarpe_episodes
    soup = BeautifulSoup(requests.get(api_url,params=params, headers=headers).json()['html'], 'html.parser')
KeyError: 'html'

```
</details>

**Comment by freddiaN** [comment] 2018-09-26 07:36
9anime is known to not work right now, so try another provider from the list of supported ones.

**Comment by ComatoseCow** [comment] 2018-09-26 14:39
Thanks! I feel stupid now but couldn't find anything on what is and isn't working.

**Comment by vn-ki** [comment] 2018-09-26 14:47
It is working for me. Can you reproduce it? Which anime did you select?

**Comment by freddiaN** [comment] 2018-09-26 19:05
I just checked it myself with `anime dl --provider 9anime 'overlord' -ll DEBUG` (and then selecting option 2 aka s1 subbed) and it seems like it was actually working :thinking:

**Comment by vn-ki** [comment] 2018-09-26 20:38
You might be using an old version of the tool. Try updating.

**Comment by ComatoseCow** [comment] 2018-09-26 22:26
So I tried again after running pip install -U anime-downloader, and have replicated the error on both windows and Ubuntu. With anime dl --provider 9anime 'My Hero Academia' -ll DEBUG and with 'overlord'.

**Comment by ComatoseCow** [comment] 2018-09-26 22:35
So I did try switching providers to kissanime and it is downloading.

**Comment by vn-ki** [comment] 2018-09-26 23:49
Paste the output of

```
anime dl 'https://9anime.is/watch/fullmetal-alchemist-brotherhood.0r7/j69y93' --episodes 1 --url -ll DEBUG
```

**Comment by ComatoseCow** [comment] 2018-09-27 00:53
Here you go! Thanks for all the help!

INFO root: anime-downloader 3.5.0
DEBUG root: Platform: Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
DEBUG root: Python 3.6.6
INFO root: Extracting episode info from page
DEBUG root: data-ts: 1537963200
{'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0', 'referer': 'https://9anime.is/watch/fullmetal-alchemist-brotherhood.0r7/j69y93'}
{'valid': True} https://www1.9anime.to/ajax/film/servers-ping?ts=1537963200&_=632
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/cli.py", line 99, in dl
    fallback_qualities=fallback_qualities)
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/anime.py", line 42, in __init__
    self.get_data()
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/anime.py", line 60, in get_data
    self._episode_urls = self._scarpe_episodes(soup)
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/nineanime.py", line 112, in _scarpe_episodes
    soup = BeautifulSoup(requests.get(api_url,params=params, headers=headers).json()['html'], 'html.parser')
KeyError: 'html'

**Comment by vn-ki** [comment] 2018-09-27 23:01
I can't reproduce this. I'm sorry.

**Comment by ComatoseCow** [comment] 2018-09-28 02:53
Also to answer your first question I can watch from 9anime

**Comment by vn-ki** [comment] 2018-10-28 18:57
Can I close this issue @ComatoseCow?

**Closed by vn-ki** 2018-10-28 18:57 UTC
