### ISSUE TITLE
gogoanime has new domain

### ISSUE THREAD

**Issue by RowanSkie** [vn-ki/anime-downloader#186] opened 2019-05-05 04:26 UTC
**Describe the bug**
Gogoanime is no longer going for gogoanime.sh but now gogoanime.io

**To reproduce**
Watch or download anything with gogoanime as the provider

```
<!--
Run the program with --log-level DEBUG and paste the output in the space below
-->
<details>
<summary>INFO root: anime-downloader 3.6.3
DEBUG root: Platform: Windows-10-10.0.17763-SP0
DEBUG root: Python 3.7.3
DEBUG root: API call URL: https://api.watchanime.cc/site/loadAjaxSearch with params {'keyword': 'cardcaptor-sakura-dub', 'id': -1, 'link_web': 'https://www1.gogoanime.sh/'}
DEBUG urllib3.util.retry: Incremented Retry for (url='/site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F'): Retry(total=9, connect=9, read=10, redirect=None, status=None)
WARNING urllib3.connectionpool: Retrying (Retry(total=9, connect=9, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02F29710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F
DEBUG urllib3.util.retry: Incremented Retry for (url='/site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F'): Retry(total=8, connect=8, read=10, redirect=None, status=None)
WARNING urllib3.connectionpool: Retrying (Retry(total=8, connect=8, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02F29870>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F
DEBUG urllib3.util.retry: Incremented Retry for (url='/site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F'): Retry(total=7, connect=7, read=10, redirect=None, status=None)
WARNING urllib3.connectionpool: Retrying (Retry(total=7, connect=7, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02F29910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F
DEBUG urllib3.util.retry: Incremented Retry for (url='/site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F'): Retry(total=6, connect=6, read=10, redirect=None, status=None)
WARNING urllib3.connectionpool: Retrying (Retry(total=6, connect=6, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02F299B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F
DEBUG urllib3.util.retry: Incremented Retry for (url='/site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F'): Retry(total=5, connect=5, read=10, redirect=None, status=None)
WARNING urllib3.connectionpool: Retrying (Retry(total=5, connect=5, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02F29A70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F
DEBUG urllib3.util.retry: Incremented Retry for (url='/site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F'): Retry(total=4, connect=4, read=10, redirect=None, status=None)
WARNING urllib3.connectionpool: Retrying (Retry(total=4, connect=4, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02F29B30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F
DEBUG urllib3.util.retry: Incremented Retry for (url='/site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F'): Retry(total=3, connect=3, read=10, redirect=None, status=None)
WARNING urllib3.connectionpool: Retrying (Retry(total=3, connect=3, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02F29BF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F
DEBUG urllib3.util.retry: Incremented Retry for (url='/site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F'): Retry(total=2, connect=2, read=10, redirect=None, status=None)
WARNING urllib3.connectionpool: Retrying (Retry(total=2, connect=2, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02F29CB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F
DEBUG urllib3.util.retry: Incremented Retry for (url='/site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F'): Retry(total=1, connect=1, read=10, redirect=None, status=None)
WARNING urllib3.connectionpool: Retrying (Retry(total=1, connect=1, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02F29D70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F
DEBUG urllib3.util.retry: Incremented Retry for (url='/site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F'): Retry(total=0, connect=0, read=10, redirect=None, status=None)
WARNING urllib3.connectionpool: Retrying (Retry(total=0, connect=0, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02F29E30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F
ERROR root: [31mHTTPSConnectionPool(host='api.watchanime.cc', port=443): Max retries exceeded with url: /site/loadAjaxSearch?keyword=cardcaptor-sakura-dub&id=-1&link_web=https%3A%2F%2Fwww1.gogoanime.sh%2F (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02F29EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))[0m</summary>
```
EDIT: Also, format's bust.

**Comment by vn-ki** [comment] 2019-05-08 18:19
Is this still hapenning?

**Comment by RowanSkie** [comment] 2019-05-09 03:09
Yeah.

**Comment by vn-ki** [comment] 2019-07-12 10:41
I can't reproduce this. Please give me the exact command you typed.

**Comment by vn-ki** [comment] 2019-07-18 07:23
@RowanSkie This is fixed in master

**Closed by vn-ki** 2019-07-18 07:23 UTC
